/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "secondary-container": "#e3e2e6",
        "on-tertiary-fixed": "#2e1500",
        "on-surface": "#191c1d",
        "surface-container-lowest": "#ffffff",
        "on-background": "#191c1d",
        "on-secondary-container": "#646468",
        "surface-container": "#edeeef",
        "surface-container-high": "#e7e8e9",
        "surface-variant": "#e1e3e4",
        "on-secondary": "#ffffff",
        "on-tertiary": "#ffffff",
        "surface-container-highest": "#e1e3e4",
        "primary-container": "#1a73e8",
        "primary": "#005bbf",
        "error": "#ba1a1a",
        "on-tertiary-fixed-variant": "#6d3a00",
        "background": "#f8f9fa",
        "surface-dim": "#d9dadb",
        "on-primary-fixed-variant": "#004493",
        "on-error-container": "#93000a",
        "on-secondary-fixed": "#1a1b1e",
        "on-error": "#ffffff",
        "on-surface-variant": "#414754",
        "secondary": "#5e5e62",
        "surface-container-low": "#f3f4f5",
        "tertiary-fixed": "#ffdcc2",
        "secondary-fixed": "#e3e2e6",
        "tertiary-fixed-dim": "#ffb77a",
        "primary-fixed-dim": "#adc7ff",
        "tertiary-container": "#b26200",
        "inverse-surface": "#2e3132",
        "error-container": "#ffdad6",
        "on-primary-fixed": "#001a41",
        "on-primary": "#ffffff",
        "on-secondary-fixed-variant": "#46474a",
        "surface": "#f8f9fa",
        "secondary-fixed-dim": "#c7c6ca",
        "tertiary": "#8e4d00",
        "outline-variant": "#c1c6d6",
        "inverse-on-surface": "#f0f1f2",
        "outline": "#727785",
        "on-tertiary-container": "#ffffff",
        "inverse-primary": "#adc7ff",
        "surface-tint": "#005bc0",
        "on-primary-container": "#ffffff",
        "surface-bright": "#f8f9fa",
        "primary-fixed": "#d8e2ff"
      },
      fontFamily: {
        "headline": ["Plus Jakarta Sans", "sans-serif"],
        "body": ["Manrope", "sans-serif"],
        "label": ["Manrope", "sans-serif"]
      },
      borderRadius: { "DEFAULT": "0.25rem", "lg": "0.5rem", "xl": "0.75rem", "2xl": "1.5rem", "full": "9999px" },
    },
  },
  plugins: [],
}
